Created Runtime-testing doc and add other files
Sydney-Informatics-Hub/rnaseqOct23_Testing pull request #13
Opened 2023-09-19 06:35 UTC by nandan75

2023-09-19 07:02 UTC, georgiesamaha requested changes
A few suggestions to remove personal correspondance and people's names from markdown documents. Keep in mind this repository is public.

2023-09-19 07:02 UTC, georgiesamaha commented on Scripts/Day2/BioCommons_Dockerfile_4.1.0_V4.0
Does the dockerfile need to be uploaded to this repository as well as https://github.com/Sydney-Informatics-Hub/Rstudio-rnaseq-contained? Would be easiest to maintain in one place.

2023-09-19 07:02 UTC, georgiesamaha commented on Scripts/Day2/Runtime-testing_D2.md
> +Hi Nandan
Our repository is now public, not appropriate for us to reveal personal correspondence, can you reword this to something like: 


```
Pawsey helpdesk suggested issue was a [known issue with Apptainer/Singularity](https://github.com/apptainer/apptainer/issues/1258) and the following workaround: 

* Configure max_loop for the loop driver to a higher value. Setting it to the same as max loop devices in /usr/local/etc/singularity/singularity.conf, which is 256 by default.
* Must do this with a kernel CMDLINE entry, because loop is compiled into the kernel on Ubuntu. It is not a module.
* Add max_loop=256 to the GRUB_CMDLINE_LINUX value in /etc/default/grub
* Run update-grub2 as root.
* Reboot the system.
* Run cat /proc/cmdline and verify max_loop=256 is present.
```

2023-09-19 07:02 UTC, georgiesamaha commented on Scripts/Day2/Runtime-testing_D2.md
> +- I had previously asked this same question to Audrey and she had provided the following solution
Remove names please

2023-09-19 07:02 UTC, georgiesamaha commented on Scripts/Day2/Runtime-testing_D2.md
> +I have used the following solution identified from blogs/ChatGPT and it has worked for a few of us at SIH:
Remove this line and replace with

```
Current workaround:
```

2023-09-19 07:02 UTC, georgiesamaha commented on Scripts/Day2/Runtime-testing_D2.md
> +Since the problem does not occur frequently (I have observed it only once on any of the instances I have worked so far). One of our collegues Giorgia has also encountered it on her insatnce. I have n
Remove names.

2023-09-19 07:02 UTC, georgiesamaha commented on Scripts/Day2/Runtime-testing_D2.md
> +Should we check with Audrey if this could be a possible issue on the trainee instances for the workshop and if we need to have any quick workarounds if this occures?
Remove name and replace with Pawsey helpdesk

2023-09-19 23:08 UTC, nandan75 commented on Scripts/Day2/BioCommons_Dockerfile_4.1.0_V4.0
Not required, but I am using it in testing - So thought it is a good place in addition to the other repo. I was thinking of uploading the latest version of everything including all these essential files for testign to this repo. But we can figure out.

2023-09-19 23:09 UTC, nandan75 commented on Scripts/Day2/Runtime-testing_D2.md
> +Hi Nandan
Sure

2023-09-19 23:09 UTC, nandan75 commented on Scripts/Day2/Runtime-testing_D2.md
> +- I had previously asked this same question to Audrey and she had provided the following solution
ok

2023-09-19 23:36 UTC, nandan75 commented on Scripts/Day2/BioCommons_Dockerfile_4.1.0_V4.0
For now I will marked this as resolved. I will remove the files if required at a later date

2023-09-19 23:49 UTC, nandan75 commented
Made the changes and pushed them to "Nandan" branch

2023-09-21 01:16 UTC, georgiesamaha approved these changes

2023-09-21 01:19 UTC, merged